[project]
name = "toothless"
version = "0.1.0"
description = "RL on GNN for EGraphs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "eggshell",
    "tensorboard>=2.17.1",
    "torch-geometric>=2.5.3",
    "torch-tb-profiler>=0.4.3",
    "torch>=2.4.0",
]

[tool.uv.sources]
eggshell = { path = "../eggshell/target/wheels/eggshell-0.0.1-cp312-cp312-macosx_11_0_arm64.whl" }
