[project]
name = "toothless"
version = "0.1.0"
description = "RL on GNN for EGraphs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "eggshell",
    "gymnasium>=0.29.1",
    "matplotlib>=3.9.2",
    "stable-baselines3>=2.3.2",
    "tensorboard>=2.17.1",
    "tensordict>=0.5.0",
    "torch-geometric>=2.5.3",
    "torch-tb-profiler>=0.4.3",
    "torch>=2.4.0",
    "tqdm>=4.66.5",
]

[tool.uv.sources]
eggshell = { path = "../eggshell/target/wheels/eggshell-0.0.1-cp312-cp312-manylinux_2_34_x86_64.whl" }
