[project]
name = "toothless"
version = "0.1.0"
description = "ML for EGraphs"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3",
    "tensorboard>=2",
    "tensordict>=0.5",
    "torch-tb-profiler>=0.4",
    "torch>=2",
    "tqdm>=4",
    "scikit-learn>=1.5.2",
    "plotly>=5.24.1",
    "kaleido==0.2.1",
    "polars>=1.21.0",
    "accelerate>=1.3.0",
    "transformers>=4.48.2",
    "scipy>=1.15.1",
    "transformers-stream-generator>=0.0.5",
    "tiktoken>=0.8.0",
    "python-dotenv>=1.0.1",
    "standard-imghdr>=3.13.0",
    "torch-geometric>=2.6.1",
    "wordninja>=2.0.0",
    "tokenizers>=0.21.0",
    "eggshell",
]

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.ruff]
# Allow lines to be as long as 120.
line-length = 120

[tool.uv.sources]
eggshell = { path = "cache/eggshell-0.0.1-cp313-cp313-manylinux_2_34_x86_64.whl" }
