[project]
name = "toothless"
version = "0.1.0"
description = "ML for EGraphs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3",
    "tensorboard>=2",
    "tensordict>=0.5",
    "torch-geometric>=2",
    "torch-tb-profiler>=0.4",
    "torch>=2",
    "tqdm>=4",
    "scikit-learn>=1.5.2",
    "pandas>=2.2.3",
    "plotly>=5.24.1",
    "kaleido==0.2.1",
    "eggshell",
]

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.uv.sources]
eggshell = { path = "../eggshell/target/wheels/eggshell-0.0.1-cp312-cp312-manylinux_2_34_x86_64.whl" }


